#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
from PIL import Image
import json

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
OUT = ROOT / "pokemon-data.ts"

CHARSET = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!$%&()*+,-/:;<=>?@[]^_{|}~"
NAME_OVERRIDES = {
    "nidoran_female": "Nidoran♀",
    "nidoran_male": "Nidoran♂",
    "mr_mime": "Mr. Mime",
    "farfetchd": "Farfetch'd",
    "missingno": "MissingNo.",
}


def rgba_to_hex(pixel: tuple[int, int, int, int]) -> str:
    return f"#{pixel[0]:02x}{pixel[1]:02x}{pixel[2]:02x}"


def display_name_from_slug(slug: str) -> str:
    if slug in NAME_OVERRIDES:
        return NAME_OVERRIDES[slug]
    return " ".join(part.capitalize() for part in slug.split("_"))


def encode_frame(path: Path) -> dict:
    image = Image.open(path).convert("RGBA")
    width, height = image.size
    pixels = [image.getpixel((x, y)) for y in range(height) for x in range(width)]
    palette: dict[str, str] = {}
    rows: list[str] = []
    next_index = 0

    for y in range(height):
        chars: list[str] = []
        for x in range(width):
            pixel = pixels[y * width + x]
            if pixel[3] == 0:
                chars.append(".")
                continue
            key = rgba_to_hex(pixel)
            if key not in palette:
                if next_index >= len(CHARSET):
                    raise RuntimeError(f"Too many colors in {path}")
                palette[key] = CHARSET[next_index]
                next_index += 1
            chars.append(palette[key])
        rows.append("".join(chars))

    encoded_palette = {token: color for color, token in palette.items()}
    return {
        "width": width,
        "height": height,
        "palette": encoded_palette,
        "rows": rows,
    }


def build() -> None:
    pokemons: list[dict] = []
    for folder in sorted(p for p in ASSETS.iterdir() if p.is_dir() and p.name[:3].isdigit()):
        slug = folder.name[4:]
        pokemons.append(
            {
                "id": folder.name[:3],
                "slug": slug,
                "displayName": display_name_from_slug(slug),
                "open": encode_frame(folder / "open.png"),
                "closed": encode_frame(folder / "closed.png"),
            }
        )

    payload = json.dumps(pokemons, indent=2, ensure_ascii=False)
    content = (
        "// Generated by scripts/generate_pokemon_data.py\n"
        "// Regenerate with: uv run --with pillow python scripts/generate_pokemon_data.py\n\n"
        "export type PokemonFrame = {\n"
        "  width: number;\n"
        "  height: number;\n"
        "  palette: Record<string, string>;\n"
        "  rows: string[];\n"
        "};\n\n"
        "export type PokemonSprite = {\n"
        "  id: string;\n"
        "  slug: string;\n"
        "  displayName: string;\n"
        "  open: PokemonFrame;\n"
        "  closed: PokemonFrame;\n"
        "};\n\n"
        f"export const POKEMON_SPRITES: PokemonSprite[] = {payload};\n"
    )
    OUT.write_text(content, encoding="utf8")
    print(f"Wrote {OUT}")
    print(f"Pokémon: {len(pokemons)}")


if __name__ == "__main__":
    build()
